services:
  api:
    build: .
    container_name: employee-api
    ports:
      - "8000:8000"
    environment:
      DB_USER: ebinejar_user
      DB_PASSWORD: Naaga@2506
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: employee_db
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: employee-db
    environment:
      POSTGRES_USER: ebinejar_user
      POSTGRES_PASSWORD: Naaga@2506
      POSTGRES_DB: employee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: