apiVersion: v1
kind: Service

metadata:
  name: employee-api
  namespace: employee-api
  labels:
    app: employee-api

spec:
  type: ClusterIP

  selector:
    app: employee-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP