apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: employee-db-pvc
  namespace: employee-api

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 10Gi